server:
  port: 4001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
spring:
  application:
    name: movie-catalog-svc
  cloud:
    loadbalancer:
      retry:
        enabled: true
ratings-data-svc:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 6
    MaxAutoRetries: 2